# Generated by Django 5.0.14 on 2026-07-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='group',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='permission',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
