# Generated by Django 5.0.14 on 2026-07-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='path',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
